require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
Style/BlockDelimiters:
  EnforcedStyle: semantic
Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/LineLength:
  Max: 80
RSpec/MultipleMemoizedHelpers:
  Max: 10
